# -*- coding: utf-8 -*-
"""aula-03-ia-cc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODA6ruwn6jW0-aZ2cKZqDWqj_OTfT88B
"""

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

#Carregar o dataset
iris = load_iris()
X = iris.data
y = iris.target
y = to_categorical(y)

#Normalização (entre 0 e 1)
scaler = StandardScaler()
X = scaler.fit_transform(X)

#Dividir o dataset entre treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                    random_state=42)

#Configurando a rede neural
model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(4,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(
    optimizer = 'adam',
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']
)

model.summary()

#Treinamento (fit)
model.fit(
    X_train, y_train,
    epochs = 60,
    batch_size = 8,
    validation_split = 0.2,
    verbose = 1
)

#Avaliação do modelo
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Acurácia {accuracy:.2f}")
print(f"Loss: {loss:.2f}")