# -*- coding: utf-8 -*-
"""aula-07-ia-cc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PzrOGhUC_4XwhWm5FfpQSvuFJ7SAYszH
"""

# blues' is not a valid value for cmap; supported values are 'Accent', 'Accent_r', 'Blues', 'Blues_r', 'BrBG', 'BrBG_r', 'BuGn', 'BuGn_r', 'BuPu', 'BuPu_r', 'CMRmap', 'CMRmap_r', 'Dark2', 'Dark2_r', 'GnBu', 'GnBu_r', 'Grays', 'Grays_r', 'Greens', 'Greens_r', 'Greys', 'Greys_r', 'OrRd', 'OrRd_r', 'Oranges', 'Oranges_r', 'PRGn', 'PRGn_r', 'Paired', 'Paired_r', 'Pastel1', 'Pastel1_r', 'Pastel2', 'Pastel2_r', 'PiYG', 'PiYG_r', 'PuBu', 'PuBuGn', 'PuBuGn_r', 'PuBu_r', 'PuOr', 'PuOr_r', 'PuRd', 'PuRd_r', 'Purples', 'Purples_r', 'RdBu', 'RdBu_r', 'RdGy', 'RdGy_r', 'RdPu', 'RdPu_r', 'RdYlBu', 'RdYlBu_r', 'RdYlGn', 'RdYlGn_r', 'Reds', 'Reds_r', 'Set1', 'Set1_r', 'Set2', 'Set2_r', 'Set3', 'Set3_r', 'Spectral', 'Spectral_r', 'Wistia', 'Wistia_r', 'YlGn', 'YlGnBu', 'YlGnBu_r', 'YlGn_r', 'YlOrBr', 'YlOrBr_r', 'YlOrRd', 'YlOrRd_r', 'afmhot', 'afmhot_r', 'autumn', 'autumn_r', 'berlin', 'berlin_r', 'binary', 'binary_r', 'bone', 'bone_r', 'brg', 'brg_r', 'bwr', 'bwr_r', 'cividis', 'cividis_r', 'cool', 'cool_r', 'coolwarm', 'coolwarm_r', 'copper', 'copper_r', 'cubehelix', 'cubehelix_r', 'flag', 'flag_r', 'gist_earth', 'gist_earth_r', 'gist_gray', 'gist_gray_r', 'gist_grey', 'gist_grey_r', 'gist_heat', 'gist_heat_r', 'gist_ncar', 'gist_ncar_r', 'gist_rainbow', 'gist_rainbow_r', 'gist_stern', 'gist_stern_r', 'gist_yarg', 'gist_yarg_r', 'gist_yerg', 'gist_yerg_r', 'gnuplot', 'gnuplot2', 'gnuplot2_r', 'gnuplot_r', 'gray', 'gray_r', 'grey', 'grey_r', 'hot', 'hot_r', 'hsv'

import matplotlib.pyplot as plt

# Get the list of available colormaps
colormaps = plt.colormaps()

print("Available colormaps in Matplotlib:")
for cmap in colormaps:
    print(f"- {cmap}")

# Or, to get a list matching the error message precisely, you can hardcode it:
# supported_cmaps_from_error = [
#     'Accent', 'Accent_r', 'Blues', 'Blues_r', 'BrBG', 'BrBG_r', 'BuGn', 'BuGn_r',
#     'BuPu', 'BuPu_r', 'CMRmap', 'CMRmap_r', 'Dark2', 'Dark2_r', 'GnBu', 'GnBu_r',
#     'Grays', 'Grays_r', 'Greens', 'Greens_r', 'Greys', 'Greys_r', 'OrRd', 'OrRd_r',
#     'Oranges', 'Oranges_r', 'PRGn', 'PRGn_r', 'Paired', 'Paired_r', 'Pastel1',
#     'Pastel1_r', 'Pastel2', 'Pastel2_r', 'PiYG', 'PiYG_r', 'PuBu', 'PuBuGn',
#     'PuBuGn_r', 'PuBu_r', 'PuOr', 'PuOr_r', 'PuRd', 'PuRd_r', 'Purples',
#     'Purples_r', 'RdBu', 'RdBu_r', 'RdGy', 'RdGy_r', 'RdPu', 'RdPu_r', 'RdYlBu',
#     'RdYlBu_r', 'RdYlGn', 'RdYlGn_r', 'Reds', 'Reds_r', 'Set1', 'Set1_r',
#     'Set2', 'Set2_r', 'Set3', 'Set3_r', 'Spectral', 'Spectral_r', 'Wistia',
#     'Wistia_r', 'YlGn', 'YlGnBu', 'YlGnBu_r', 'YlGn_r', 'YlOrBr', 'YlOrBr_r',
#     'YlOrRd', 'YlOrRd_r', 'afmhot', 'afmhot_r', 'autumn', 'autumn_r', 'berlin',
#     'berlin_r', 'binary', 'binary_r', 'bone', 'bone_r', 'brg', 'brg_r', 'bwr',
#     'bwr_r', 'cividis', 'cividis_r', 'cool', 'cool_r', 'coolwarm', 'coolwarm_r',
#     'copper', 'copper_r', 'cubehelix', 'cubehelix_r', 'flag', 'flag_r',
#     'gist_earth', 'gist_earth_r', 'gist_gray', 'gist_gray_r', 'gist_grey',
#     'gist_grey_r', 'gist_heat', 'gist_heat_r', 'gist_ncar', 'gist_ncar_r',
#     'gist_rainbow', 'gist_rainbow_r', 'gist_stern', 'gist_stern_r',
#     'gist_yarg', 'gist_yarg_r', 'gist_yerg', 'gist_yerg_r', 'gnuplot',
#     'gnuplot2', 'gnuplot2_r', 'gnuplot_r', 'gray', 'gray_r', 'grey', 'grey_r',
#     'hot', 'hot_r', 'hsv'
# ]
# print("\nSupported colormaps from the previous error message:")
# for cmap in supported_cmaps_from_error:
#     print(f"- {cmap}")

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from PIL import Image
from tensorflow.keras import layers, models

(x_train, y_train) , (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train, x_test = x_train / 255.0 , x_test / 255.0

i = 1
plt.imshow(x_test[i], cmap='plasma')
plt.show()

model = models.Sequential([
    layers.Flatten(input_shape=(28,28)),
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# Definição do modelo
model.compile(
    optimizer = 'adam',
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)

#Treino
model.fit(
    x_train,
    y_train,
    epochs=5,
    batch_size=32,
    verbose=1
)

#teste da acuracia
loss, acuracia = model.evaluate(x_test, y_test)
print(f'Acurácia: {acuracia}')

# Teste com as proprias imagens do dataset
i = 14
img = x_test[i].reshape(1,28,28)

pred = model.predict(img).argmax()

plt.imshow(x_test[i], cmap='plasma')
plt.title(f"Real: {y_test[i]} | Previsto: {pred}")
plt.show()

# carregar a imagem
img = Image.open('imagem-da-evolução-do-pichu.jpg').convert("L")
img = img.resize((28,28))

#converter para array e normalizar
img_array = np.array(img) / 255.0

# Caso img fundo branco
# img_array = 1 - img_array

#Ajustar o shape / formato
img_array = img_array.reshape(1,28,28)

#Classificacao
pred = model.predict(img_array)
digito = pred.argmax()

plt.imshow(img, cmap='plasma')
plt.title(f"Previsão: {digito}")
plt.axis("off")
plt.show()