# -*- coding: utf-8 -*-
"""aula-05-IA-CC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVYJBabXsmVJ_DpkVPcok_1lNSShk_9A
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest

df = pd.read_csv("transacoes_anomalias.csv")

print(f"Primeira \n linha do dataset: {df.head()}")
print("\n")
print(df.head())

print(f"Informação do dataset: {df.info()}")

# Seleção das features numericas
feature = ["valor","frequencia","tempo_entre_compras"]
X = df[feature]

#Padronização dos dados
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

#Treinamento do isolation forest
model = IsolationForest(
    n_estimators=100,
    contamination=0.05,
    random_state=42
)

model.fit(X_scaled)

#Predições de anomalias
# -1 para anomalia / 1 para normal
df['anomaly'] = model.predict(X_scaled)

#Score de anomali(quanto menor, mais anormal ou anomalia)
df["anomaly_score"] = model.decision_function(X_scaled)

#Rotulo mais legivel
df["anomaly_label"] = df["anomaly"].map({1 : "normal" , -1: "anômalo"})

#Quantidade de registros encontrados
print(f"Registros por classes: {df['anomaly_label'].value_counts()}")

plt.figure(figsize=(7,5))
sns.scatterplot(
    data=df,
    x = "valor",
    y = "tempo_entre_compras",
    hue = "anomaly_label",
    palette = {"normal": "blue", "anômalo" : "gold"}
)
plt.title("Detecção de anomalias - Valor x Tempo entre compras")
plt.show()

#Nova colunas dos graficos das anomalia da transações anomalias
df

# from google.colab import sheets
# sheet = sheets.InteractiveSheet(df=df)

plt.figure(figsize=(7,5))
sns.scatterplot(
    data = df,
    x = "valor",
    y = "frequencia",
    hue = "anomaly_label",
    palette = {"normal" : "gold", "anômalo" : "green"}
)
plt.title("Detecção de anomalias - Valor x Frequencia")
plt.show()