# -*- coding: utf-8 -*-
"""aula-06-ia-cc-live.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATXZxBCrTRALdXcvF0MsGAWX19QF0me5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from mlxtend.frequent_patterns import apriori , association_rules
warnings.filterwarnings("ignore" , category=DeprecationWarning)

#Carregar o dataset
df = pd.read_csv("basket.csv")

pd.set_option("display.max_columns",None)
df = df.drop(columns=["transacao"])
print(df.head())

#Aplicar o algoritmo apriori
frequent_itemsets = apriori(
    df,
    min_support=0.2,
    use_colnames=True
)

print("Itemsets/Subconjuntos frequentes:")
print(frequent_itemsets.sort_values(by = "support", ascending=True))

#Gerar as regras de associação
rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.5
)

print("Regra de associação")
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth",None)
print(rules)

#Filtrar as regras relevantes
rules_filtered = rules[
    (rules['lift'] > 1) &
    (rules['confidence'] >= 0.6)
].sort_values(by='lift', ascending=False)

print("Regras relevantes")
print(rules_filtered[["antecedents", "consequents","support","confidence","lift"]])

#novas colunas
df

#Insights para o gerente
print("Insights para o gerente")

for _, row in rules_filtered.iterrows():
  antecedentes = ", ".join(list(row["antecedents"]))
  consequentes = ", ".join(list(row['consequents']))
  print(
      f"clientes que compram [{antecedentes}]"
      f"tendem a comprar [{consequentes}]"
      f"(confiança=row{row['confidence']:.2f}, lift={row["lift"]:.2f})"
  )