# -*- coding: utf-8 -*-
"""aula-04-IA-CC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12antQBHsmc44JX_0-s___F0-GYBSdfZp

#comando do terminal pycharm
"""

# 📂 Navegação e Arquivos
# Comando	O que faz
# ls	Lista os arquivos da pasta atual
# ls -R	Lista todos os arquivos, incluindo subpastas
# cd nome_da_pasta	Entra em uma pasta
# cd ..	Volta para a pasta anterior
# pwd	Mostra o caminho completo de onde você está agora
# 🐍 Ambiente Virtual (venv)
# Comando	O que faz
# python3 -m venv venv	Cria o ambiente virtual chamado "venv"
# source venv/bin/activate	Ativa o ambiente (essencial para rodar o código)
# deactivate	Desativa o ambiente virtual
# 📦 Gerenciamento de Bibliotecas (pip)
# Comando	O que faz
# pip install pandas	Instala a biblioteca Pandas
# pip uninstall nome	Remove uma biblioteca instalada
# pip list	Mostra todas as bibliotecas instaladas no seu venv
# pip freeze > requirements.txt	Salva a lista de bibliotecas do projeto num arquivo
# pip install -r requirements.txt	Instala tudo o que está listado no arquivo de requisitos
# 🚀 Execução
# Comando	O que faz
# python src/evalute.py	Executa o script que está dentro da pasta src
# python --version	Verifica qual versão do Python está ativa no momento

"""# Comando do terminal pycharm"""

# source venv/bin/activate (Tentativa inicial de ativar o ambiente)
# ls -l (Listar arquivos com detalhes)
# ll (Comando não encontrado)
# ls (Listar arquivos)
# python3.8 -m venv venv (Criar o ambiente virtual)
# sorce venv\bin\activate (Erro de digitação em "source" e uso de barra invertida)
# source venv\bin\activate (Uso de barra invertida, que o macOS/Linux não reconhece para caminhos)
# source venv/bin/activate (Ativação correta do venv)
# python3.8 evalute.py (Tentativa de rodar o arquivo fora da pasta src)
# ls (Verificar pastas)
# ll (Comando não encontrado)
# ls -la (Listar todos os arquivos, incluindo ocultos)
# python3.8 src/evalute.py (Tentativa de rodar o script; deu erro de falta do pandas)
# pip install panda (Erro de digitação: instalou a biblioteca panda em vez de pandas)
# python3.8 src/evalute.py (Erro de pandas persistiu)
# pip install panda (Tentativa repetida)
# ls -R (Listagem recursiva de todas as pastas e arquivos do projeto)

"""#comando do terminal pycharm

"""

# para executar o diretorio src-1 train.py

# source venv/bin/activate
# python src/preprocesso.py
# python src-1/train.py

# uma dica de oura se quiser juntar dois diretorios separados para poder ver o resultado:
# python src-1/train.py && python src-2/evaluate.py

"""#da aula ia sobre explainer ia em portugues ia explicativa"""

#Biblioteca
import pandas as pd
import numpy as np
import shap
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

#1 Carregar dataset do aluno universitario
df = pd.read_csv("dataset_alunos_universitarios.csv")

# 1 linha do dataset do aluno universitario
print("\nPrimeiro linhas do dataset: ")
print(df.head())

#Esse é a informação do dataset do aluno universitario
print("\nInformação do dataset: ")
print(df.info())

# 2 Pré processamento
#Converter variáveis categóricas para numéricas
le_dict = {}

for col in df.select_dtypes(include='object').columns:
  le = LabelEncoder()
  df[col] = le.fit_transform(df[col])
  le_dict[col] = le

#Separar features e target
X = df.drop("status_curso", axis=1)
y = df["status_curso"]

print("\nFeatures: ")
print(X.columns)

#3 divisão treino / teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

# 5 avaliar modelo
y_pred = model.predict(X_test)

print("\nRelatório de classificação: ")
print(classification_report(y_test, y_pred))

#Feature importance

importances = model.feature_importances_

features_importances = pd.DataFrame({
    "feature" : X.columns,
    "importances" : importances
})

features_importances = features_importances.sort_values(
    by="importances",
    ascending=False
)

print(f"Feature importance")
print(features_importances)

plt.figure()
plt.barh(features_importances["feature"], features_importances["importances"])
plt.gca().invert_yaxis()
plt.title("feature importance")
plt.xlabel("Importância")
plt.ylabel("Feature")
plt.show()

#Sha
#Criar o explainer
explainer = shap.TreeExplainer(model, X_train)

#Calcular os valores do SHAP
shap_values = explainer.shap_values(X_test)

#Selecionar uma classes (evadiu ou concluiu)
shap_class = shap_values[:,:,1]

#Gerar gráfico beeswarm (enxame de abelhas)
shap.summary_plot(
    shap_class,
    X_test,
    feature_names = X_test.columns
)

# Explicação de uma previsão individual

index = 10
shap.plots.waterfall(
    shap.Explanation(
        values=shap_class[index],
        base_values=explainer.expected_value[1],
        data=X_test.iloc[index],
        feature_names=X_test.columns
    )
)

# Exemplo de previsão com explicação

index = 10
sample = X_test.iloc[[index]]
prediction = model.predict(sample)[0]
prob = model.predict_proba(sample)[0]

print(f"Previsão: {prediction}")
print(f"Probabilidade: {prob}")

print(f"Valores da amostra: {sample}")