# -*- coding: utf-8 -*-
"""aula-02-IA-CC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJkQTaula6YQ-8OkZMFlPpkhhCD9u-KF

#meu codigo do mes passado
"""

#esse é o codigo da aula passada no mes passado
#no dia 26 de fevereiro

#1 - Importações
#2 - Coleta dos dados da série temporal
#3 - Visualização das séries temporal
#4 - Normalização dos dados
#5 - Criação das janelas temporais
#6 - Separação treino / teste(sem embaralhar)
#7 - Construção do modelo lstm
#8 - Treinamento do modelo
#9 - Avaliação do modelo
#10 - Visualização das previsões
#11 - Previsão do próximo dia

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install tensorflow yfinance

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , LSTM
from tensorflow.keras.callbacks import EarlyStopping

ticker = "tsla"
start_date = "2015-01-01"
end_date = None

df = yf.download(ticker, start=start_date, end=end_date)
print()
print(df.head())
print(df.tail())

series = df[['Close']].dropna()
print(series)

#3 visualização dos graficos do titanic
plt.figure()
plt.plot(series)
plt.title(f"Preço de fechamento - {ticker}")
plt.xlabel("Data")
plt.ylabel("Preço")
plt.show()

#4 Normalização dos dados
scaler = MinMaxScaler(feature_range=(0,1))
series_scaled = scaler.fit_transform(series)
print(series_scaled)

#5 Criação das janelas temporais
def create_window(data, window_size):
  X, y = [], []
  for i in range(len(data) - window_size):
    X.append(data[i:i+window_size])
    y.append(data[i+window_size])
  return np.array(X), np.array(y)

window_size = 30

X, y = create_window(series_scaled, window_size)

print(f"Formato do x: {X.shape}")
print(f"Formato do y: {y.shape}")

#6 Seperação treino / teste(sem embaralhar)
split = int(0.8 * len(X))

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

print(f"Treino: {X_train.shape}")
print(f"Teste: {X_test.shape}")

# 7 - construção do modelo lstm
model = Sequential()
model.add(LSTM(50, activation='tanh', input_shape=(window_size, 1)))
model.add(Dense(1))

model.compile(
    optimizer="adam",
    loss='mse'
)

model.summary()

#8 Treinamento do modelo
early_stop = EarlyStopping(
    monitor = "val_loss",
    patience = 50,
    restore_best_weights = True
)

history = model.fit (
    X_train,
    y_train,
    batch_size = 50,
    epochs = 120,
    validation_split = 0.2,
    callbacks = [early_stop],
    verbose = 2
)

# 9. avaliação do modelo
y_pred = model.predict(X_test)

y_test_inv = scaler.inverse_transform(y_test)
y_pred_inv = scaler.inverse_transform(y_pred)

rmse = np.sqrt(mean_squared_error(y_test_inv, y_pred_inv))
print(f"RMSE: {rmse}")

# 10. Visualização das previsões
plt.figure()
plt.plot(series.index[-len(y_test):] , y_test_inv, label="Valor real")
plt.plot(series.index[-len(y_test):], y_pred_inv, label="Valor previsto")
plt.title(f"Previsão de preço de fechamento - {ticker} com LSTM")
plt.xlabel("Data")
plt.ylabel("Preço")
plt.legend()
plt.show()

#11. Previsão de fechamento do próximo dia
last_window = series_scaled[-window_size:]
last_window = last_window.reshape(1, window_size, 1)

next_day_pred = model.predict(last_window) # valores entre 0 e 1
next_day_price = scaler.inverse_transform(next_day_pred) # valores previsto em dólares

print(f"Previão de preço da {ticker} para o proximo dia $ {next_day_price[0][0]:.2f}")